version: 2.1
orbs:
  node: circleci/node@4.0.0
jobs:
  install-node:
    docker:
      - image: circleci/node:12.18.1
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: |
              node --version
              yarn run build-windows

    
workflows:
  node-tests:
    jobs:
      - install-node
